spring:
  application:
    api-prefix: /api/v1
    name: spring-boot-rest-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: XEEL0X56
    secretKey: 9ATJAUXZ1CRMQISER27KMAMDBDE28HOZ
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

